### ISSUE TITLE
Overlinking with zlib

### ISSUE THREAD

**Issue by Dave-Allured** [NCAR/ncplot#5]
In the current Makefile for ncplot, instructions for Mac OS have a dependency on zlib via linker option `-lz`.  Is this overlinking?  Is zlib directly accessed from anywhere within ncplot itself?
```
#LIBS = -lXm -lXt -lX11 -lnetcdf -ll -lgsl -lm -lpng -lz -lpthread
```
Indeed, zlib is a secondary dependency via netcdf.  However, I could not find any recognizable direct references to zlib headers or functions from ncplot code.  Also I tried omitting -lz from the link command, and that gave a working dynamically linked executable with no complaints.  I am building in a MacPorts environment.  I think `-lz` might be a holdover from old static build instructions for netcdf.

**Comment by topher800** [comment]
zlib was originally included because libpng required it.

-lm and -lz removed.  Neither seemed to be required for CentOS 7, 8, and MacOS Catalina.

**Comment by Dave-Allured** [comment]
Thank you.  FYI this will support the recent addition of `ncplot` in Macports.
